### ISSUE TITLE
Cant see the duck

### ISSUE THREAD

**Issue by MaSven** [ovelius/dart2d#5]
After the games load the duck is invisible. Pressing down let me see a little dot that i can but can only go left or right.

![image](https://cloud.githubusercontent.com/assets/9138252/22550692/88a776a4-e951-11e6-98b7-cf0216b4e272.png)

The console gives this errors.

```1977001025-idpiframe.js:53 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at ia (https://ssl.gstatic.com/accounts/o/1977001025-idpiframe.js:4:170)
    at x.F (https://ssl.gstatic.com/accounts/o/1977001025-idpiframe.js:13:168)
    at Object.k.tb (https://ssl.gstatic.com/accounts/o/1977001025-idpiframe.js:9:159)
    at S.h.start (https://ssl.gstatic.com/accounts/o/1977001025-idpiframe.js:52:502)
    at Object.Mb [as startIdpIFrame] (https://ssl.gstatic.com/accounts/o/1977001025-idpiframe.js:88:212)
    at https://accounts.google.com/o/oauth2/iframe:1:414
h.start @ 1977001025-idpiframe.js:53
Mb @ 1977001025-idpiframe.js:88
(anonymous) @ iframe:1
apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:45 Uncaught TypeError: Cannot read property 'apply' of undefined
    at bG.bm (wormworld.dart.js:4642)
    at bG.d9 (wormworld.dart.js:4643)
    at nK.dart.nK.$1 (wormworld.dart.js:7595)
    at Object.ft (wormworld.dart.js:1356)
    at dart.hM (wormworld.dart.js:4594)
    at wormworld.dart.js:4699
    at onSignIn (wormworld.html:49)
    at _.fp._.k.q0 (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:392)
    at _.lH._.k.q0 (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:394)
    at ix (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:536)
bm @ wormworld.dart.js:4642
d9 @ wormworld.dart.js:4643
dart.nK.$1 @ wormworld.dart.js:7595
ft @ wormworld.dart.js:1356
dart.hM @ wormworld.dart.js:4594
(anonymous) @ wormworld.dart.js:4699
onSignIn @ wormworld.html:49
_.k.q0 @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:392
_.k.q0 @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:394
ix @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:536
(anonymous) @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:538
h.o0 @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:53
xs @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:56
Wq @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:56
_.C.uea @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:55
Ap @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:49
setTimeout (async)
tp @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:45
(anonymous) @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:56
Ap @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:49
Promise.resolve (async)
um @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:49
_.Qp @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:49
er @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:55
hq @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:54
(anonymous) @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:50
g @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:538
a.callback @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:532
Mw @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:521
(anonymous) @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:526
(anonymous) @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:522
g @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:93
c @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=client/…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:84
postMessage (async)
(anonymous) @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=rpc,shi…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:49
setTimeout (async)
call @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=rpc,shi…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:49
call @ apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.d_kubyVm1cc.O/m=rpc,shi…1/d=1/ed=1/am=AQ/rs=AGLTcCPoS6_X-zvrvVfAmYArBp1iBhcVIQ/cb=gapi.loaded_0:66
W @ 75729278-postmessagerelay.js:14
Y @ 75729278-postmessagerelay.js:14
(anonymous) @ 75729278-postmessagerelay.js:15
wormworld.dart.js:5071 Uncaught TypeError: Cannot read property 'gbb' of undefined
    at fh.f2 (wormworld.dart.js:5071)
    at kt.dart.kt.$2 (wormworld.dart.js:5265)
    at ag.dart.ag.lB (wormworld.dart.js:4984)
    at Object.eval (eval at ex (wormworld.dart.js:1), <anonymous>:2:38)
    at Object.ft (wormworld.dart.js:1356)
    at dart.hM (wormworld.dart.js:4594)
    at DataConnection.<anonymous> (wormworld.dart.js:7642)
    at DataConnection.EventEmitter.emit (util.js:209)
    at DataConnection._handleDataMessage (peer.js:541)
    at RTCDataChannel._dc.onmessage (peer.js:529)
```

**Comment by ovelius** [comment]
Nice issue title :) 

There is at least one race condition when loading the initial scripts that can cause this.

Was there any white text messages displayed at the top left corner?
Did the problem go away after reloading the page?

**Comment by MaSven** [comment]
No the problem was still there after reloading the page.

**Comment by MaSven** [comment]
I tried to build it to find the error myself but when i try to open it, after pub build and pub serve, i get this error.
```
Build completed with 1 errors.
[web]  GET  → Could not find asset dart2d|web.
[web]  GET favicon.ico → Could not find asset dart2d|web/favicon.ico.
``` 

Or is this not the appropiate way of building this application ?

**Comment by ovelius** [comment]
A clean clone and pub get + pub serve should suffice to allow dartium to run it. 

Note that the script loading race condition will likely not appear in a local build as the script causing it can't run on a local build (it's a login script).
 

Still I'm curious as to if there are any white messages showing up in the top left corner while reproaing this?  

I can't reproduce this myself, on multiple devices. Just to make sure the browser cache was also cleared before repro ? (E.g. clear cache load page and the reload page)

Cheers

**Comment by MaSven** [comment]
Ok after clearing the cache it works. Yes there was some white text but it was too quick to read also the backround is not the best. The text in black would improve the readability i think
